#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-esoa-api-gateway.name" . }}-system-user-realm-role-mappings-configmap
  labels:
    {{- include "eric-esoa-api-gateway.labels" .| nindent 4 }}
  annotations:
    {{- include "eric-esoa-api-gateway.annotations" . | nindent 4 }}
data:
  system-user-realm-role-mappings.json: |
    [
      {
        "name": "RouteAdmin"
      }
    ]
