apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "eric-esoa-api-gateway.name" . }}-create-rbac-configuration-hook
  labels:
    app: {{ template "eric-esoa-api-gateway.name" . }}
    chart: {{ template "eric-esoa-api-gateway.chart" . }}
  {{- include "eric-esoa-api-gateway.labels" .| nindent 4 }}
  annotations:
  {{- include "eric-esoa-api-gateway.annotations" .| nindent 4 }}
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 8
  template:
    metadata:
      annotations:
      {{- include "eric-esoa-api-gateway.annotations" .| nindent 8 }}
      labels:
        app: {{ template "eric-esoa-api-gateway.name" . }}
      {{- include "eric-esoa-api-gateway.labels" .| nindent 8 }}
    spec:
      {{- if  .Values.imageCredentials.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.pullSecret | quote }}
      {{- else if .Values.global.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.pullSecret | quote }}
      {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ template "eric-esoa-api-gateway.name" . }}-sa
      {{- if .Values.tolerations }}
      tolerations:
        {{ toYaml .Values.tolerations | indent 8 | trim }}
      {{- end }}
      containers:
        - name: keycloak-client
          image: {{ template "eric-esoa-so-library-chart.imagePath" (dict "imageId" "keycloakClient" "values" .Values "files" .Files) }}
          imagePullPolicy: {{ .Values.global.registry.imagePullPolicy | quote }}
          env:
          - name: IAM_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.iam.adminSecret | quote }}
                key: {{ .Values.global.iam.userKey | quote }}
          - name: IAM_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.iam.adminSecret | quote }}
                key: {{ .Values.global.iam.passwordKey | quote }}
          args:
          - "create"
          - "authz"
          - "--keycloak_hostname={{ .Values.global.hosts.iam }}"
          - "--keycloak_user=$(IAM_ADMIN_USER)"
          - "--keycloak_password=$(IAM_ADMIN_PASSWORD)"
          - "--client_name={{ .Values.global.iam.clientId }}"
          - "--provider={{ .Chart.Name }}"
          - "--config=/config/rbac-configuration.json"
          volumeMounts:
          - name: create-rbac-configuration-volume
            mountPath: /config
          - name: create-cacert-volume
            mountPath: /mnt/certs
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false # kecloak client does write on the root file system
            runAsNonRoot: true
            runAsUser: 128474 # due to a limitation in the keycloak client image, it needs to be just this id
            capabilities:
              drop:
                - "all"
      nodeSelector: {{- include "eric-esoa-so-library-chart.nodeSelector" . | nindent 8 }}
      volumes:
      - name: create-rbac-configuration-volume
        configMap:
          name: {{ .Chart.Name }}-rbac-configuration-configmap
          defaultMode: 0777
      - name: create-cacert-volume
        secret:
          secretName: {{ .Values.global.iam.cacert.secretName }}
          items:
            - key: {{ .Values.global.iam.cacert.key }}
              path: {{ .Values.global.iam.cacert.filePath }}
