---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-esoa-api-gateway.name" . }}
  labels:
  {{- include "eric-esoa-api-gateway.labels" .| nindent 4 }}
  annotations:
        {{- include "eric-esoa-api-gateway.prometheus" .| nindent 4 }}
        {{- include "eric-esoa-api-gateway.annotations" . | nindent 4 }}
spec:
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily | quote }}]
  {{- end }}
  {{- end }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: {{ template "eric-esoa-api-gateway.name" . }}
